//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class CatalogoProductos
    {
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.DropDownList ddlProducto;
        protected global::System.Web.UI.WebControls.Label lblPrecioUnitario;
        protected global::System.Web.UI.WebControls.TextBox txtCantidad;
        protected global::System.Web.UI.WebControls.Button btnAgregarItem;
        protected global::System.Web.UI.WebControls.GridView dgvItems;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.Button btnConfirmar;
    }
}
