//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class Clientes
    {
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        protected global::System.Web.UI.WebControls.HiddenField hfId;

        protected global::System.Web.UI.WebControls.TextBox txtDNI;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        protected global::System.Web.UI.WebControls.TextBox txtDireccion;

        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;

        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.GridView dgvClientes;
    }
}
