//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class ComprasFormulario
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlProveedor;

        protected global::System.Web.UI.WebControls.DropDownList ddlProducto;

        protected global::System.Web.UI.WebControls.TextBox txtCantidad;

        protected global::System.Web.UI.WebControls.TextBox txtPrecioUnitario;

        protected global::System.Web.UI.WebControls.Button btnAgregarItem;

        protected global::System.Web.UI.WebControls.Label lblMensaje;

        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.GridView dgvItems;

        protected global::System.Web.UI.WebControls.Label lblTotal;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;

        protected global::System.Web.UI.WebControls.Panel pnlPropuestas;

        protected global::System.Web.UI.WebControls.GridView dgvPropuestas;
    }
}
