//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class Compras
    {
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::AplicacionWebComercio.BarraFiltros ctrlFiltros;
        protected global::System.Web.UI.WebControls.GridView dgvCompras;
    }
}
