//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class ComprasFormulario
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlProveedor;

        protected global::System.Web.UI.WebControls.DropDownList ddlProducto;

        protected global::System.Web.UI.WebControls.TextBox txtCantidad;

        protected global::System.Web.UI.WebControls.TextBox txtPrecioUnitario;

        protected global::System.Web.UI.WebControls.Button btnAgregarItem;

        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.GridView dgvItems;

        protected global::System.Web.UI.WebControls.Label lblTotal;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;
    }
}
