//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class Compras
    {
        protected global::System.Web.UI.WebControls.GridView dgvCompras;
    }
}
