//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class Marcas
    {
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        protected global::System.Web.UI.WebControls.HiddenField hfId;

        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;

        protected global::System.Web.UI.WebControls.GridView dgvMarcas;

        protected global::System.Web.UI.WebControls.Label lblError;
    }
}
