//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class Productos
    {
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        protected global::System.Web.UI.WebControls.HiddenField hfId;

        protected global::System.Web.UI.WebControls.TextBox txtCodigo;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        protected global::System.Web.UI.WebControls.TextBox txtPrecio;

        protected global::System.Web.UI.WebControls.TextBox txtStockMinimo;

        protected global::System.Web.UI.WebControls.TextBox txtPorcentajeGanancia;

        protected global::System.Web.UI.WebControls.DropDownList ddlMarca;

        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;

        protected global::AplicacionWebComercio.BarraFiltros ctrlFiltros;
        
        protected global::System.Web.UI.WebControls.GridView dgvProductos;
    }
}
