//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class Proveedores
    {
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        protected global::System.Web.UI.WebControls.HiddenField hfId;

        protected global::System.Web.UI.WebControls.TextBox txtRazonSocial;

        protected global::System.Web.UI.WebControls.TextBox txtCuit;

        protected global::System.Web.UI.WebControls.TextBox txtDireccion;

        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;

        protected global::AplicacionWebComercio.BarraFiltros ctrlFiltros;
        
        protected global::System.Web.UI.WebControls.GridView dgvProveedores;
    }
}
