//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class RegistroCliente
    {
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtDni;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtApellido;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtUsuario;
        protected global::System.Web.UI.WebControls.TextBox txtContrasena;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmar;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
    }
}
