//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio {
    
    
    public partial class ReportesDinamicos {
        
        protected global::System.Web.UI.WebControls.DropDownList ddlPlantillas;
        protected global::System.Web.UI.WebControls.Button btnCargarPlantilla;
        protected global::System.Web.UI.WebControls.TextBox txtNombrePlantilla;
        protected global::System.Web.UI.WebControls.Button btnGuardarPlantilla;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoReporte;
        protected global::System.Web.UI.WebControls.TextBox txtFechaDesde;
        protected global::System.Web.UI.WebControls.TextBox txtFechaHasta;
        protected global::System.Web.UI.WebControls.Button btnGenerar;
        protected global::System.Web.UI.WebControls.Button btnExportar;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.GridView dgvReporte;
    }
}
