//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liInicio;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liClientes;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liProveedores;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liProductos;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liMarcas;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCategorias;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCompras;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liVentas;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liUsuarios;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTrazabilidad;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCatalogo;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liMisCompras;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCambiarContrasena;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCrearCuenta;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLogin;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLogout;
    }
}
