//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWebComercio
{
    public partial class VentasFormulario
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlCliente;

        protected global::System.Web.UI.WebControls.DropDownList ddlFormaPago;

        protected global::System.Web.UI.WebControls.DropDownList ddlCantidadCuotas;

        protected global::System.Web.UI.WebControls.DropDownList ddlProducto;

        protected global::System.Web.UI.WebControls.TextBox txtCantidad;

        protected global::System.Web.UI.WebControls.Button btnAgregarItem;

        protected global::System.Web.UI.WebControls.Label lblMensaje;

        protected global::System.Web.UI.WebControls.GridView dgvItems;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;
    }
}
